setup:
	ansible-playbook -i inventory/hosts.yml playbook.yml -K

zsh:
	ansible-playbook -i inventory/hosts.yml playbook.yml -K --tags zsh

base:
	ansible-playbook -i inventory/hosts.yml playbook.yml -K --tags base

docker:
	ansible-playbook -i inventory/hosts.yml playbook.yml -K --tags docker
