- name: Remove old Zsh config (deterministic reset)
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_env.HOME }}/.oh-my-zsh"
    - "{{ ansible_env.HOME }}/.zshrc"
    - "{{ ansible_env.HOME }}/.oh-my-zsh-custom"
  tags: [zsh]

- name: Get zsh path
  command: which zsh
  register: zsh_path
  changed_when: false
  tags: [zsh]

- name: Set default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_path.stdout }}"
  ignore_errors: true
  tags: [zsh]

- name: Install Oh My Zsh
  shell: |
    export RUNZSH=no
    export CHSH=no
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
  tags: [zsh]

- name: Create plugin directory
  file:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins"
    state: directory
  tags: [zsh]

- name: Install plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
    depth: 1
    force: yes
  loop:
    - {
        name: "zsh-syntax-highlighting",
        repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git",
      }
    - {
        name: "zsh-autosuggestions",
        repo: "https://github.com/zsh-users/zsh-autosuggestions.git",
      }
  tags: [zsh]

- name: Create theme directory
  file:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes"
    state: directory
  tags: [zsh]

- name: Create custom theme
  copy:
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/meutema.zsh-theme"
    content: |
      # Meu tema customizado para Oh My Zsh
      PROMPT='%F{green}%n@%m %F{blue}%~ %F{yellow}$ %f'
      RPROMPT='%F{cyan}%*%f'
      ZSH_THEME_GIT_PROMPT_PREFIX='%F{magenta}('
      ZSH_THEME_GIT_PROMPT_SUFFIX=')%f'
      ZSH_THEME_GIT_PROMPT_DIRTY='%F{red}*%f'
      ZSH_THEME_GIT_PROMPT_CLEAN='%F{green}✔%f'
  tags: [zsh]
