- name: Configure git aliases
  community.general.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - { name: "alias.a", value: "add -A" }
    - { name: "alias.l", value: "log" }
    - { name: "alias.s", value: "status" }
    - { name: "alias.c", value: "commit -m" }
    - { name: "alias.pm", value: "push -uf origin main" }
  tags: [git]
